### ISSUE TITLE
Sign up to newsletter functionality

### ISSUE THREAD

**Issue by fadeomar** [yalla-coop/chiltern-website#46] opened 2021-11-30 13:01 UTC
After further investigation, unfortunately Mailchimp does not provide the functionality for you to directly add tags with a custom form submission. We have worked out though that you can create a new column and then store a value there. So this means we have 3 potential options for you to choose:

- send data directly from Webflow directly to Mailchimp without Tags

- send data directly from Webflow to Mailchimp and store the value (e.g. General, Fundraising) in a new column (SUBSCRIBED_WITH_FORM) on your contacts table so you can still filter etc easily 

- use Zapier which would enable us to send tags with the data and store this in Mailchimp (here's an explanation of how it's done in case you wanted to see: https://www.youtube.com/watch?v=kVx3pr5yc_Q) You current paid version of Zapier gives you up to 750 actions per month and 20 zaps so this should cover your expected usage. To confirm, if we did this route, we could set this up ourselves (not reliant on Tim) as it's not dealing with Salesforce

Can you please let us know which option you'd like to proceed with? Very happy to also jump on a call to talk through if easier.

**Comment by thejoefriel** [comment] 2021-12-16 11:11
Redundant issue as duplicate of stuff covered in #10

**Closed** 2022-01-05 18:01 UTC
Labels: priority-4
